export const submissionFormStyles = {
  wrapper: 'mx-auto max-w-4xl',
  headerIcon: 'h-6 w-6',
  alertSection: 'mb-6',
  alertBookRow: 'flex items-center gap-2 text-sm',
  alertBookImage: 'rounded object-cover',
  alertBookTitle: 'font-medium',
  alertBookAuthor: 'text-muted-foreground',
  alertBooksList: 'mt-2 space-y-2',
  continueLink: 'mt-2 p-0',
  formContainer: 'space-y-6',
  sectionTitle: 'text-lg font-semibold',
  sectionCard: 'border-dashed',
  sectionCardTitle: 'text-base',
  isbnRow: 'flex gap-2',
  isbnInput: 'flex-1',
  lookupIcon: 'h-4 w-4',
  lookupIconSpin: 'h-4 w-4 animate-spin',
  lookupText: 'ml-2',
  searchButton: 'w-full',
  searchIcon: 'mr-2 h-4 w-4',
  searchIconSpin: 'mr-2 h-4 w-4 animate-spin',
  googleResults: 'mt-4 space-y-2',
  googleResultsLabel: 'text-sm font-medium',
  googleResultItem:
    'flex w-full cursor-pointer items-start gap-3 rounded-lg border p-3 text-left transition hover:bg-accent',
  googleResultImage: 'rounded object-cover',
  googleResultInfo: 'flex-1',
  googleResultTitle: 'font-medium',
  googleResultAuthor: 'text-sm text-muted-foreground',
  googleResultDate: 'text-xs text-muted-foreground',
  detailsSection: 'space-y-4',
  gridTwoCols: 'grid grid-cols-1 gap-4 md:grid-cols-2',
  authorWrapper: 'relative',
  authorDropdown: 'absolute z-10 mt-1 w-full',
  authorDropdownContent: 'p-2',
  authorOption: 'w-full cursor-pointer rounded p-2 text-left hover:bg-accent',
  descriptionTextarea: 'min-h-32 resize-none',
  categoriesBadges: 'mt-2 flex flex-wrap gap-2',
  categoryRemove: 'ml-1',
  categoryRemoveIcon: 'h-3 w-3',
  coverContent: 'mt-6 min-h-32 space-y-2',
  coverPreview: 'flex items-center gap-4',
  coverImage: 'h-40 w-auto rounded-md object-cover',
  saleToggle: 'flex items-center justify-between rounded-lg border p-4',
  saleToggleLabel: 'space-y-0.5',
  priceWrapper: 'relative',
  priceIcon:
    'absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground',
  priceInput: 'pl-9',
  saleCardContent: 'space-y-4',
  saleTitleIcon: 'h-4 w-4',
  submitRow: 'flex gap-4',
  submitButton: 'flex-1',
  submitIcon: 'mr-2 h-4 w-4',
  submitIconSpin: 'mr-2 h-4 w-4 animate-spin',
};
