import type { Metadata } from 'next';
import { Bona_Nova } from 'next/font/google';
import '@/assets/styles/globals.css';

const bonaNova = Bona_Nova({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bonaNova.className} antialiased`}>{children}</body>
    </html>
  );
}
